CREATE TABLE [dbo].[CATEGORIA]
(
[CODCAT] [int] NOT NULL IDENTITY(1, 1),
[ESTCAT] [char] (1) COLLATE Modern_Spanish_CI_AS NULL,
[NOMCAT] [varchar] (20) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CATEGORIA] ADD CONSTRAINT [PK__CATEGORI__CB56521EB9C8F7E3] PRIMARY KEY CLUSTERED  ([CODCAT]) ON [PRIMARY]
GO
