CREATE TABLE [dbo].[PRODUCTO]
(
[CODPRO] [int] NOT NULL IDENTITY(1, 1),
[NOMPRO] [varchar] (30) COLLATE Modern_Spanish_CI_AS NOT NULL,
[MARPRO] [varchar] (30) COLLATE Modern_Spanish_CI_AS NOT NULL,
[MODPRO] [varchar] (30) COLLATE Modern_Spanish_CI_AS NOT NULL,
[PREPRO] [decimal] (8, 2) NOT NULL,
[CODCAT] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUCTO] ADD CONSTRAINT [PK__PRODUCTO__B6D7A72CDFDF3A27] PRIMARY KEY CLUSTERED  ([CODPRO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUCTO] ADD CONSTRAINT [PRODUCTO_CATEGORIA] FOREIGN KEY ([CODCAT]) REFERENCES [dbo].[CATEGORIA] ([CODCAT])
GO
