CREATE TABLE [dbo].[PERSONA]
(
[CODPER] [int] NOT NULL IDENTITY(1, 1),
[NOMPER] [varchar] (30) COLLATE Modern_Spanish_CI_AS NOT NULL,
[APEPER] [varchar] (40) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DNIPER] [char] (8) COLLATE Modern_Spanish_CI_AS NOT NULL,
[TIPPER] [char] (1) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DIRPER] [varchar] (30) COLLATE Modern_Spanish_CI_AS NOT NULL,
[ESTPER] [char] (1) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PERSONA] ADD CONSTRAINT [PK__PERSONA__B6D609ABFB3EB30D] PRIMARY KEY CLUSTERED  ([CODPER]) ON [PRIMARY]
GO
